### ISSUE TITLE
Flag PR

### ISSUE THREAD

**Issue by laisfrigerio** [welksonramos/flags-brazil#7]
Pull request [#8](https://github.com/welksonramos/flags-brazil/pull/8)

**Comment by laisfrigerio** [comment]
@welksonramos  entrei no site e flag que eu desenvolvi não está aparecendo. Será que esqueci de algo? https://flags-brazil.now.sh/

**Comment by welksonramos** [comment]
Está correto, só está faltando eu atualizar o site mesmo irei fazer isso daqui a pouco 😉

**Comment by laisfrigerio** [comment]
Obrigada! Fechando a issue!!!

**Comment by welksonramos** [comment]
@laisfrigerio Como a ZEIT que detinha o *Now* agora é Vercel o link do repositório foi atualizado para https://flags-brazil.vercel.app
Sua contribuição já está lá, se quiser pode manter seu repositório atualizado também 😃
